############# English navigation ##############

# # main menu
# [[main]]
# name = "Home"
# url = "/"
# weight = 1





[[main]]
name = "Blog"
url = "/blog"
weight = 1

[[main]]
name = "Gallery"
url = "/gallery"
weight = 2

[[main]]
name = "Portfolio"
url = "/portfolio"
weight = 3

[[main]]
name = "Book Reviews"
url = "/book_reviews"
weight = 4

[[main]]
name = "Book Release"
url = "/book-release"
weight = 5

[[main]]
name = "About"
url = "/about"
weight = 6



# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 5

[[footer]]
name = "Book Reviews"
url = "/book_reviews"
weight = 3

[[footer]]
name = "Blog"
url = "/blog"
weight = 1

[[footer]]
name = "Portfolio"
url = "/portfolio"
weight = 2

[[footer]]
name = "Gallery"
url = "/gallery"
weight = 4

