############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "About"
url = "/about"
weight = 2

[[main]]
name = "Book Reviews"
url = "/book_reviews"
weight = 3

[[main]]
name = "Blog"
url = "/blog"
weight = 4

[[main]]
name = "Contact"
url = "/contact"
weight = 5


# footer menu
[[footer]]
name = "About"
url = "/about"
weight = 1

[[footer]]
name = "Book Reviews"
url = "/book_reviews"
weight = 2

[[footer]]
name = "Blog"
url = "/blog"
weight = 3

[[footer]]
name = "Contact"
url = "/contact"
weight = 4
