name = "Pratheba"
license = "MIT"
licenselink = "https://github.com/PrathebaCV/pratheba.com_hugo_simple/blob/main/LICENSE"
description = "Pratheba's blog"
homepage = "https://pratheba.com"
min_version = "0.141.0"

tags = [
  "blog",
  "responsive",
  "minimal",
  "personal",
  "light",
  "dark",
  "multilingual",
  "landing",
  "contact",
  "dark mode",
  "tailwindcss",
]

features = [
  "Search",
  "Multilingual",
  "Dark Mode",
  "Taxonomies",
]

[author]
name = "Pratheba"
homepage = "https://www.pratheba.com"

[original]
author = "Pratheba"
homepage = "https://www.pratheba.com"
repo = "https://github.com/PrathebaCV/pratheba.com_hugo_simple"
